export const PRODUCT_LIST = [
  {
    id: 0,
    img: 'http://webimg.calobye.com/wys2/file_attach/2021/12/14/210514_isolate_bulk_thumb.jpg',
    title: '락토프리 고단백 프로틴 파우더',
    category: '보충제',
    price: 77900,
    choice: true,
    new: true,
    size: ['F'],
  },
  {
    id: 1,
    img: 'https://kalovis.com/web/product/big/202203/4dcbcd7e62f12e0881c7d2a6b84538e9.png',
    title: '[헬스&프로틴] 잇팅 카카오맛',
    category: '보충제',
    price: 35000,
    choice: true,
    new: true,
    size: ['2box(14일분)', '4box(28일분)'],
  },
  {
    id: 2,
    img: 'http://webimg.calobye.com/wys2/file_attach/2023/03/08/protein_sparkling_thumb_pc_model%20_02.jpg',
    title: '국내 최초 프로틴 스파클링 음료 레몬라임',
    category: '보충제',
    price: 39900,
    choice: true,
    new: true,
    size: ['12개입', '24개입'],
  },
  {
    id: 3,
    img: 'http://webimg.calobye.com/wys2/file_attach/2022/06/08/timesale_thumb_pc_active_L_arginine1000.jpg',
    title: '칼로바이 ACTIVE L-아르기닌 1000',
    category: '영양제',
    price: 9900,
    choice: false,
    new: true,
    size: ['180정(2개월분)'],
  },
  {
    id: 4,
    img: 'http://webimg.calobye.com/wys2/file_attach/2023/01/25/perfect_power_magnesium_open_thumb_web.jpg',
    title: '퍼펙트 파워 마그네슘',
    category: '영양제',
    price: 11900,
    choice: true,
    new: false,
    size: ['1box(3개월분)'],
  },
  {
    id: 5,
    img: 'http://webimg.calobye.com/wys2/file_attach//2023/02/10/230213_perpect_power_arginine_6200_pc_thumb_1.jpg',
    title: '퍼펙트 파워 아르기닌 6200',
    category: '영양제',
    price: 19900,
    choice: false,
    new: false,
    size: ['1box(3개월분)'],
  },
  {
    id: 6,
    img: 'http://webimg.calobye.com/wys2/file_attach/2022/05/27/220602_health_beginner_package_pc_thumb.jpg',
    title: '헬린이 스타트업 패키지',
    subTitle: '퍼파쉐 아이솔레이트 1개+BCAA 1개+L아르기닌 1개+쉐이커 +2,000원',
    category: '보충제',
    price: 91900,
    choice: true,
    new: false,
    size: ['F'],
  },
  {
    id: 7,
    img: 'http://webimg.calobye.com/wys2/file_attach/2022/10/05/bbak_tension_stick_pc_thumb.jpg',
    title: '피지컬랩 빡텐션 포 라임',
    category: '보충제',
    price: 19900,
    choice: false,
    new: true,
    size: ['14포', '42포', '84포'],
  },
  {
    id: 8,
    img: 'http://webimg.calobye.com/wys2/file_attach/2022/10/05/bbak_potion_stick_thumb.jpg',
    title: '피지컬랩 빡포션 포 블루베리',
    category: '보충제',
    price: 19900,
    choice: true,
    new: true,
    size: ['14포', '42포', '84포'],
  },
  {
    id: 9,
    img: 'http://webimg.calobye.com/wys2/file_attach/2022/10/05/bbak_potion_bottle_24ea_tray_pc_thumb.jpg',
    title: '피지컬랩 빡포션 캔 피치',
    category: '보충제',
    price: 21900,
    choice: false,
    new: true,
    size: ['12개입', '24개입'],
  },
  {
    id: 10,
    img: 'http://webimg.calobye.com/wys2/file_attach/2022/11/01/5_0_diet%20project_thumb.jpg',
    title: '5.0 다이어트 프로젝트',
    category: '보충제',
    price: 19900,
    choice: true,
    new: false,
    size: ['5일분', '10일분'],
  },
  {
    id: 11,
    img: 'http://webimg.calobye.com/wys2/file_attach/2022/06/14/perfect_powershake_isolate_1kg_3flavor_thumb_web.jpg',
    title: '퍼펙트 파워쉐이크 아이솔레이트 1kg',
    category: '보충제',
    price: 49800,
    choice: true,
    new: true,
    size: ['초코맛', '딸기맛', '바나나맛'],
  },
  {
    id: 12,
    img: 'http://webimg.calobye.com/wys2/file_attach/2023/01/09/timesale_physicalgallery_package_event_pc_thumb_02.jpg',
    title: '퍼펙트 파워쉐이크 김계란 패키지',
    category: '보충제',
    price: 61900,
    choice: true,
    new: true,
    size: ['32개입', '64개입'],
  },
  {
    id: 13,
    img: 'http://webimg.calobye.com/wys2/file_attach/2023/03/08/230308_powershake_wheypack_reservation_pc_thumb.jpg',
    title: '칼로바이 퍼펙트 파워쉐이크 포대유청',
    category: '보충제',
    price: 49900,
    choice: false,
    new: false,
    size: ['F'],
  },
  {
    id: 14,
    img: 'http://webimg.calobye.com/wys2/file_attach/2021/12/14/dameal_balance_thumb.jpg',
    title: '다밀 밸런스 음료 오곡맛',
    category: '보충제',
    price: 15900,
    choice: false,
    new: false,
    size: ['16팩', '64팩'],
  },
  {
    id: 15,
    img: 'http://webimg.calobye.com/wys2/file_attach/2022/05/27/211210_protein_pack_thumb.jpg',
    title: '우리가족 단백질 패키지 Ⅰ',
    category: '보충제',
    subTitle: '라이프 프로틴 2개 + 마시는 라이프 프로틴 16팩 + 쉐이커',
    price: 54800,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 16,
    img: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSmA2W0wcE8_57TD9GNYj63Ieo2dKBnY4jQOjSHO5Y78YEnucq9PShMTavqcEZQcuAsOoMskx5eL0F6-wIn-evWJiCy6QbJjNZfz4ZAUiTD&usqp=CAE',
    title: '음파 운동기구 진동운동기 덜덜이 실내운동',
    category: '헬스기구',
    price: 83000,
    choice: false,
    new: false,
    size: ['F'],
  },
  {
    id: 17,
    img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ4M3oTz6bdd-CW9jB92dQM0-dCL_1Ngbgm7LW09JhvL81QwqIF_TM6EMfjVsFRoG7WewrgZ1icZSRjrSXMpTPtGNuDJzjjfmtJuKNlI-l3&usqp=CAE',
    title: '추감기 리스트롤러 전완근 운동 기구(와이어타입)',
    category: '헬스기구',
    price: 14800,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 18,
    img: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSylxW3_hE9Q8Qoypb9FGqudiMdQ1o_Bp9MGlEvTswvMGFz0L62GLMS9hdm3c6_xojC2gKIj4buIUy0FxSdRvKq5ue2Y3kUM5ACZkuT8mHLf9fAa_4cUYYz&usqp=CAE',
    title: '누워서하는 편한운동 다이어트 실내운동기구 밸런스 스윙',
    category: '헬스기구',
    price: 89100,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 19,
    img: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT7CSNWV30_fd0h8fCNnwxiJzeotdqmRoRbS3GREMT8eyI52nxSm-fYX54O0OYA4LMw1hvr9MNuBmppZCXlo7MM0_XYBptJ3ejsm8z2GDAub9d6_j6rgDOneQ&usqp=CAE',
    title: '[바디엑스(BODYX)]바디엑스 토탈 홈짐 H88 홈짐세트 실내운동기구',
    category: '헬스기구',
    price: 507500,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 20,
    img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQlVgNCR19im2DtVqhtCWUBTvlFbjfN9fZL85_Jm481z6E7aNlZnucWbTIXpSjBIgF41HXQoAJavdtG93FmNuGL7nu4lU5l&usqp=CAE',
    title: '멜킨 로잉머신 볼트윅 블랙 가정용 전신 운동기구 헬스 조정 노젓기 홈트',
    category: '헬스기구',
    price: 352720,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 21,
    img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQCOW7rCrJey3tuWGc06W8j6gO2tEyrUkWmspMh9gKJLH6OXICj0hAgv4MQJMLpwVcl1vSMtDf0bq_b363_HwtFsGqe2ValRA&usqp=CAE',
    title: '걷기운동기구 천국의계단 클라이머 사다리운동 스테퍼',
    category: '헬스기구',
    price: 306640,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 22,
    img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQZFKvtJko1SdW0XLJY5ons1jl7A2UhEmofnnEeGeg1WcOfmzyKjuHUFO5mGv1MXMbaFUi1SUUaEmJuXp3lxm7D4ZBTC89mZcKUZOSWhmrg_jgQpIao7_tC&usqp=CAE',
    title: '비스펙 레그익스텐션 하체운동 다리운동 웨이트 관절운동 헬스기구',
    category: '헬스기구',
    price: 109000,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 23,
    img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTXtecQFdiycY0KzLmbK3pr5Uh4hEQNBhj4mW92Xn3vD9jIhP2FhuVwPPuSc_DMq7xkEaSmYgIvxzV9FJ_694us96oO2pQCMgUvaVset-umWVUhl0vNNmiT&usqp=CAE',
    title: '엑스킹 로잉머신 뱃살 복근 전신 코어 실내 운동기구',
    category: '헬스기구',
    price: 128000,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 24,
    img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQCOW7rCrJey3tuWGc06W8j6gO2tEyrUkWmspMh9gKJLH6OXICj0hAgv4MQJMLpwVcl1vSMtDf0bq_b363_HwtFsGqe2ValRA&usqp=CAE',
    title: '걷기운동기구 천국의계단 클라이머 사다리운동 스테퍼',
    category: '헬스기구',
    price: 306640,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 25,
    img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR3JXi0kO-1CDJiCLUnOgdNYW3PNjo3rffOky-2KIovzdgvDYJ5vc2rcqFjCguCUrx_z7SOF0BrOGqny37pDbH1mcPa2gLV3L55S-YM5jO0pk6FySvyUfx19g&usqp=CAE',
    title: '스텝퍼 무소음 걷기 실내 운동 가정용 피트니스 기구 남녀 소형 제자리',
    category: '헬스기구',
    price: 155200,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 26,
    img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTVHVAkIGIrJNIEsntTaLTUljf898iIvLZNYYb12hzXJWiw_0J-l_EtJAOoekwPrnaUd6AviWxKMSy9HSOA5MQ8GZoiGRflAiERtqMJFlgPl8t08-2t-CRkuw&usqp=CAE',
    title: '숀리 엑스바이크 플래티넘 실내 자전거 유산소 운동 기구 가정용 하체 접이식 와이드형',
    category: '헬스기구',
    price: 148740,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 27,
    img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQCOW7rCrJey3tuWGc06W8j6gO2tEyrUkWmspMh9gKJLH6OXICj0hAgv4MQJMLpwVcl1vSMtDf0bq_b363_HwtFsGqe2ValRA&usqp=CAE',
    title: '걷기운동기구 천국의계단 클라이머 사다리운동 스테퍼',
    category: '헬스기구',
    price: 306640,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 28,
    img: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQJoVpDdYkUawPbrG1EoNnhIcCbcMFukvzB7UusdqWUtI3T6c-cD7COXlbfoEVX92eGkKDFs9JE6d_1IK6EmeS5EhyK9FeN&usqp=CAE',
    title: '악마철봉 랫풀다운그립 홈짐 벽고정철봉 등운동기구 스트레칭 가정철봉',
    category: '헬스기구',
    price: 10000,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 29,
    img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQCOW7rCrJey3tuWGc06W8j6gO2tEyrUkWmspMh9gKJLH6OXICj0hAgv4MQJMLpwVcl1vSMtDf0bq_b363_HwtFsGqe2ValRA&usqp=CAE',
    title: '걷기운동기구 천국의계단 클라이머 사다리운동 스테퍼',
    category: '헬스기구',
    price: 306640,
    choice: false,
    new: false,
    size: ['16팩', '64팩'],
  },

  {
    id: 30,
    img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT4dMIrGnFft4Cv7Xdecpl6fHJM3Me5LfwIKUqHnK6KgGNZhTW_dk_RkqWak1RiiqanqMkSPLyyiJzWOpT8YdGU4u6ft2wShTl3PV5hXQqbgt4JKGlnC9zQ&usqp=CAE',
    title: '어시스트 치닝디핑 철봉 턱걸이 가정용 운동 헬스기구',
    category: '헬스기구',
    price: 223200,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 31,
    img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQIALOwhmv7oWxpcvT94i5UppOmZl2NflCSSHupE_k8f4ei_sWRXEVgST3mus6blYXPEkB8Tyhr1qudY4EkB0xlIigAtLIG&usqp=CAE',
    title: '엑사이더 저소음 완벽폴딩 런닝머신 런닝홈 EW731 트레드밀 워킹머신 헬스 운동기구',
    category: '헬스기구',
    price: 499000,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 32,
    img: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS6ZNfCG9NgtSFaenEnQSC83tZFMXJ-lXcw4pepYgbMkN2-LAxyoRTk3zfwaf13INYvGci7pDECotow5QKd6qqdZoRbux8ynVK2FilDwv6I-lUkzAA5tQ48&usqp=CAE',
    title: '네오맥스 체스트프레스 NX401 (웨이트운동기구)',
    category: '헬스기구',
    price: 3550000,
    choice: false,
    new: false,
    size: ['F'],
  },

  {
    id: 33,
    img: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSny62icfxo8ECnTcaI1Pl1Sn38v8IQRX5RsXXM8J3t00YXmwjEDdH8DMs020w2S3wXKpOUyImgLJOnKqg30HEHKlkU9Li4MQ&usqp=CAE',
    title: '국산 전동 거꾸리 4종 헬스기구 스트레칭 거꾸리',
    category: '헬스기구',
    price: 585000,
    choice: false,
    new: false,
    size: ['F'],
  },
  {
    id: 34,
    img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ4w9BBK9jLgmy0nUYiEGJmUyB2aRUfcyu-57MKva6z575PguEuSVyrdZbT6gPLO6YaoGopqLR8irT2f1V88UYa0g9_FKDql_vdt-L-sp3OrZsjeDP6APTY&usqp=CAE',
    title: '하체운동기구 스쿼트머신 헬스장 피트니스 풀세트 스미스 머신 딥스 중량벤치 백스쿼트머신',
    category: '헬스기구',
    price: 3880000,
    choice: false,
    new: false,
    size: ['F'],
  },
]
